# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
env:
  global:
    - secure: "XFAGsCXxWF1OKET++clUcQyri63wV7AFxSzMsbnEqk7IidakTS1QsjbBxudGNei2m9q32hQmG3L5/GLRDgeSWdfXtjr7Dw+3pD0OIPBl/Cjwm+0qMhlIW//QfqFov+pBamQbwA72x5BpRyh/Zc6jp9V8hPtnjG9V92RwfszvHOc="

language: cpp
compiler:
  - gcc
# - clang
#branches:
#  only:
#    - master
before_install:
  # Update repos
  - sudo apt-get update -qq
  # Install dependencies
  - sudo apt-get install build-essential cmake libogg-dev libvorbis-dev libopenal-dev libxxf86vm-dev libcurl4-openssl-dev libfribidi-dev libbluetooth-dev
  # Install mesa from an other repo (a newer version is required)
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu quantal main restricted"
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
  - sudo apt-get update -qq
  - sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev
script:
  #  Build commands
  - mkdir build
  - cd build
  ##- cmake .. -DCMAKE_BUILD_TYPE=Debug -DCHECK_ASSETS=off
  - cmake .. -DCHECK_ASSETS=off
  - make VERBOSE=1 -j 4 
  - pwd
  - ls -l bin
  - date
  - echo -n GITHUB_TEST_TOKEN '  '
  - echo $GITHUB_TEST_TOKEN
##deploy:
##  provider: releases
##  api-key: $GITHUB_TOKEN
##  file: build/bin/supertuxkart
##  skip_cleanup: true
##  on:
    #tags - when set to true, Travis CI only deploys on tagged builds
    ##tags: true
    #all_branches - when set to true, trigger release from any branch if passing
##    all_branches: true
    #branch - branch or list of branches to release from if passing
    #repo - only trigger a build for the given repository, to play nice with forks
notifications:
  ##irc:
    ##channels:
    ##  - "irc.freenode.org#stk"
    ##skip_join: false
    ##use_notice: true
    ##template:
      #- "[%{commit}: %{author}] %{message}"
      #- "%{build_url}"
      ##- "[%{repository}#%{branch} @%{commit}] %{author}): %{message}"
      ##- "Diff: %{compare_url}"
      ##- "Build: %{build_url}"

