#!/bin/bash
#linux-chroot-command

echo
echo '======================================================'
echo 'inside linux-chroot-command begin...'
echo

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "cd ${DIR}"
cd ${DIR}

echo pwd
pwd

echo 'ls -l /chroot*'
ls -l /chroot*

echo 'ls -l'
ls -l

  mkdir build-trusty64
  cd build-trusty64

echo pwd
pwd

  date
  ##- cmake .. -DCMAKE_BUILD_TYPE=Debug -DCHECK_ASSETS=off
  cmake .. -DCHECK_ASSETS=off -DCMAKE_INSTALL_PREFIX=../stkopt
  ##make VERBOSE=1 -j 4
  make -j 4
  make install
  echo pwd
  pwd
  echo 'ls -l bin'
  ls -l bin
  echo 'ls -l ../stkopt'
  ls -l ../stkopt
  
  mv ../stkopt/bin/supertuxkart ../stkopt/
  mv ../stkopt/share/supertuxkart/data ../stkopt/
  rm -r ../stkopt/bin ../stkopt/share
  
  echo " " > ../stkopt/readme
  date >> ../stkopt/readme
  echo " " >> ../stkopt/readme
  echo "Get by svn co : " >> ../stkopt/readme
  echo "  https://svn.code.sf.net/p/supertuxkart/code/stk-assets" >> ../stkopt/readme
  echo "Then link into data/ these assets dirs: " >> ../stkopt/readme
  echo "  karts music sfx textures tracks" >> ../stkopt/readme
  echo " " >> ../stkopt/readme
  echo "Download links: " >> ../stkopt/readme
  echo "  curl https://ming-openbox.rhcloud.com/uploadlist/upload_file_list.txt" >> ../stkopt/readme
  echo "  curl -o t.tgz https://ming-openbox.rhcloud.com/phpsrc/file_download.php?file=stkopt.tgz-020" >> ../stkopt/readme
  echo " " >> ../stkopt/readme
  echo "Run the game: run the \"go\" command." >> ../stkopt/readme
  echo " " >> ../stkopt/readme

  echo '#!/bin/bash' > ../stkopt/go
  echo 'DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"' >> ../stkopt/go
  echo '"HOME=$DIR $DIR/supertuxkart"' >> ../stkopt/go
  chmod a+rx ../stkopt/go

  echo 'ls -l ../stkopt'
  ls -l ../stkopt
  
  tar zcf stkopt.tgz ../stkopt/
  mv stkopt.tgz bin
  date
  objcopy --only-keep-debug bin/supertuxkart bin/supertuxkart.dbgsymbols
  strip bin/supertuxkart
  mkdir bindbg
  cp bin/supertuxkart.dbgsymbols bindbg
  objcopy --add-gnu-debuglink=bindbg/supertuxkart.dbgsymbols bin/supertuxkart
  mv bin/supertuxkart bin/supertuxkart-trusty64
  echo 'ls -l bin'
  ls -l bin
  date

echo pwd
pwd

echo 'ls -l /chroot*'
ls -l /chroot*

echo 'ls -l'
ls -l

echo
echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
echo "TRAVIS_BRANCH $TRAVIS_BRANCH "
echo

echo
echo 'inside linux-chroot-command end.'
echo '======================================================'
echo

